# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
#
# Codigo gerado automaticamente (ver README)

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1249, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_SerialPorts = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_SerialPorts.setGeometry(QtCore.QRect(20, 60, 71, 21))
        self.comboBox_SerialPorts.setObjectName("comboBox_SerialPorts")
        self.pushButton_UpdatePorts = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_UpdatePorts.setGeometry(QtCore.QRect(20, 10, 75, 23))
        self.pushButton_UpdatePorts.setObjectName("pushButton_UpdatePorts")
        self.comboBox_Baudrate = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Baudrate.setGeometry(QtCore.QRect(20, 110, 69, 22))
        self.comboBox_Baudrate.setObjectName("comboBox_Baudrate")
        self.comboBox_Baudrate.addItem("")
        self.comboBox_Baudrate.addItem("")
        self.comboBox_Baudrate.addItem("")
        self.comboBox_Baudrate.addItem("")
        self.comboBox_Baudrate.addItem("")
        self.comboBox_Baudrate.addItem("")
        self.pushButton_StartProgram = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_StartProgram.setGeometry(QtCore.QRect(20, 150, 101, 41))
        self.pushButton_StartProgram.setObjectName("pushButton_StartProgram")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(30, 90, 51, 16))
        self.label_41.setObjectName("label_41")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(10, 230, 91, 16))
        self.label_35.setObjectName("label_35")
        self.doubleSpinBox_UpdateTime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_UpdateTime.setGeometry(QtCore.QRect(20, 250, 62, 22))
        self.doubleSpinBox_UpdateTime.setDecimals(3)
        self.doubleSpinBox_UpdateTime.setProperty("value", 0.01)
        self.doubleSpinBox_UpdateTime.setObjectName("doubleSpinBox_UpdateTime")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(740, 10, 511, 561))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(190, -20, 131, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(230, 270, 131, 16))
        self.label_9.setObjectName("label_9")
        self.graphicsView_3 = PlotWidget(self.tab_3)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 20, 481, 241))
        self.graphicsView_3.setAutoFillBackground(True)
        self.graphicsView_3.setFrameShape(QtWidgets.QFrame.Box)
        self.graphicsView_3.setFrameShadow(QtWidgets.QFrame.Plain)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_3.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_3.setForegroundBrush(brush)
        self.graphicsView_3.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.TextAntialiasing)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = PlotWidget(self.tab_3)
        self.graphicsView_4.setGeometry(QtCore.QRect(10, 290, 481, 241))
        self.graphicsView_4.setAutoFillBackground(True)
        self.graphicsView_4.setFrameShape(QtWidgets.QFrame.Box)
        self.graphicsView_4.setFrameShadow(QtWidgets.QFrame.Plain)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_4.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_4.setForegroundBrush(brush)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(190, 0, 131, 16))
        self.label_23.setObjectName("label_23")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(230, 270, 131, 16))
        self.label_24.setObjectName("label_24")
        self.graphicsView_7 = PlotWidget(self.tab_4)
        self.graphicsView_7.setGeometry(QtCore.QRect(10, 20, 481, 241))
        self.graphicsView_7.setAutoFillBackground(True)
        self.graphicsView_7.setFrameShape(QtWidgets.QFrame.Box)
        self.graphicsView_7.setFrameShadow(QtWidgets.QFrame.Plain)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_7.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_7.setForegroundBrush(brush)
        self.graphicsView_7.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.TextAntialiasing)
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.graphicsView_8 = PlotWidget(self.tab_4)
        self.graphicsView_8.setGeometry(QtCore.QRect(10, 290, 481, 241))
        self.graphicsView_8.setAutoFillBackground(True)
        self.graphicsView_8.setFrameShape(QtWidgets.QFrame.Box)
        self.graphicsView_8.setFrameShadow(QtWidgets.QFrame.Plain)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_8.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_8.setForegroundBrush(brush)
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(190, 0, 131, 16))
        self.label_25.setObjectName("label_25")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.Temperatura = QtWidgets.QWidget()
        self.Temperatura.setObjectName("Temperatura")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.Temperatura)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 360, 41, 16))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.Temperatura)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 70, 41, 16))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_21 = QtWidgets.QLabel(self.Temperatura)
        self.label_21.setGeometry(QtCore.QRect(9, 50, 51, 16))
        self.label_21.setObjectName("label_21")
        self.label_20 = QtWidgets.QLabel(self.Temperatura)
        self.label_20.setGeometry(QtCore.QRect(20, 341, 54, 13))
        self.label_20.setObjectName("label_20")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.Temperatura)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 130, 41, 16))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_22 = QtWidgets.QLabel(self.Temperatura)
        self.label_22.setGeometry(QtCore.QRect(0, 110, 81, 16))
        self.label_22.setObjectName("label_22")
        self.label_7 = QtWidgets.QLabel(self.Temperatura)
        self.label_7.setGeometry(QtCore.QRect(230, 0, 91, 16))
        self.label_7.setObjectName("label_7")
        self.label_13 = QtWidgets.QLabel(self.Temperatura)
        self.label_13.setGeometry(QtCore.QRect(250, 270, 91, 16))
        self.label_13.setObjectName("label_13")
        self.graphicsView_6 = PlotWidget(self.Temperatura)
        self.graphicsView_6.setGeometry(QtCore.QRect(70, 290, 421, 241))
        self.graphicsView_6.setAutoFillBackground(True)
        self.graphicsView_6.setFrameShape(QtWidgets.QFrame.Box)
        self.graphicsView_6.setFrameShadow(QtWidgets.QFrame.Plain)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_6.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_6.setForegroundBrush(brush)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_5 = PlotWidget(self.Temperatura)
        self.graphicsView_5.setGeometry(QtCore.QRect(70, 20, 421, 241))
        self.graphicsView_5.setAutoFillBackground(True)
        self.graphicsView_5.setFrameShape(QtWidgets.QFrame.Box)
        self.graphicsView_5.setFrameShadow(QtWidgets.QFrame.Plain)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_5.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_5.setForegroundBrush(brush)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.tabWidget_2.addTab(self.Temperatura, "")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(254, 51, 481, 241))
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.Box)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Plain)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView.setForegroundBrush(brush)
        self.graphicsView.setObjectName("graphicsView")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(204, 91, 41, 16))
        self.lineEdit.setObjectName("lineEdit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(204, 401, 51, 16))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(454, 31, 51, 16))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(204, 151, 41, 16))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(204, 131, 51, 16))
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(204, 351, 41, 16))
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(454, 301, 81, 16))
        self.label_3.setObjectName("label_3")
        self.graphicsView_2 = PlotWidget(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(254, 321, 481, 241))
        self.graphicsView_2.setAutoFillBackground(True)
        self.graphicsView_2.setFrameShape(QtWidgets.QFrame.Box)
        self.graphicsView_2.setFrameShadow(QtWidgets.QFrame.Plain)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_2.setBackgroundBrush(brush)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(204, 421, 41, 16))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(204, 71, 41, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(204, 371, 41, 16))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 360, 191, 82))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(120, 10, 70, 17))
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 450, 81, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_10.addWidget(self.label_26)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_10.addWidget(self.label_31)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_11.addWidget(self.label_27)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_11.addWidget(self.label_32)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_12.addWidget(self.label_28)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_12.addWidget(self.label_33)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_13.addWidget(self.label_29)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_13.addWidget(self.label_34)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_14.addWidget(self.label_30)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_14.addWidget(self.label_36)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(120, 40, 101, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1249, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_UpdatePorts.setText(_translate("MainWindow", "Update Ports"))
        self.comboBox_Baudrate.setItemText(0, _translate("MainWindow", "250000"))
        self.comboBox_Baudrate.setItemText(1, _translate("MainWindow", "1000000"))
        self.comboBox_Baudrate.setItemText(2, _translate("MainWindow", "500000"))
        self.comboBox_Baudrate.setItemText(3, _translate("MainWindow", "115200"))
        self.comboBox_Baudrate.setItemText(4, _translate("MainWindow", "345600"))
        self.comboBox_Baudrate.setItemText(5, _translate("MainWindow", "9600"))
        self.pushButton_StartProgram.setText(_translate("MainWindow", "Start Program"))
        self.label_2.setText(_translate("MainWindow", "Serial Port"))
        self.label_41.setText(_translate("MainWindow", "Baud Rate"))
        self.label_35.setText(_translate("MainWindow", "Update Time [s]"))
        self.label_8.setText(_translate("MainWindow", "Potencia instantanea (W)"))
        self.label_9.setText(_translate("MainWindow", "Energia (J/min)"))
        self.label_23.setText(_translate("MainWindow", "Potencia instantanea (W)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Potencia e Energia"))
        self.label_24.setText(_translate("MainWindow", "FFT corrente"))
        self.label_25.setText(_translate("MainWindow", "FFT tensao"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "FFT"))
        self.label_21.setText(_translate("MainWindow", "Medio LM"))
        self.label_20.setText(_translate("MainWindow", "Medio"))
        self.label_22.setText(_translate("MainWindow", "Med Termopar"))
        self.label_7.setText(_translate("MainWindow", "Temperatura (C)"))
        self.label_13.setText(_translate("MainWindow", "Iluminancia"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Temperatura), _translate("MainWindow", "Temperatura e iluminancia"))
        self.label_6.setText(_translate("MainWindow", "RMS (mA)"))
        self.label.setText(_translate("MainWindow", "Tensão (V)"))
        self.label_5.setText(_translate("MainWindow", "RMS (V)"))
        self.label_10.setText(_translate("MainWindow", "Pico (mA)"))
        self.label_3.setText(_translate("MainWindow", "Corrente (mA)"))
        self.label_4.setText(_translate("MainWindow", "Pico (V)"))
        self.label_11.setText(_translate("MainWindow", "Sample Rate (Hz) "))
        self.label_16.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "FPS "))
        self.label_15.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "Lost Frames"))
        self.label_17.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "Data points"))
        self.label_19.setText(_translate("MainWindow", "0"))
        self.checkBox.setText(_translate("MainWindow", "Apply Gain"))
        self.label_26.setText(_translate("MainWindow", "A0 (V)"))
        self.label_31.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "A1 (V)"))
        self.label_32.setText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "A2 (V)"))
        self.label_33.setText(_translate("MainWindow", "0"))
        self.label_29.setText(_translate("MainWindow", "A3 (V)"))
        self.label_34.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "A4 (V)"))
        self.label_36.setText(_translate("MainWindow", "0"))
        self.checkBox_2.setText(_translate("MainWindow", "Freeze plots"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
